### ISSUE TITLE
Question / Feature Request:  Ability to edit app.config or add custom mapreduce beam files

### ISSUE THREAD

**Issue by mikrofusion** [basho-labs/riak-docker#3]
Hi, 

We've been spiking on Riak / erlang / Elixir for work as we are hoping to these technologies for a large upcoming project.

I'm currently using this docker image to run Riak in a cluster locally.  I am trying to get mapreduce working per the instructions here:
http://docs.basho.com/riak/kv/2.1.4/developing/app-guide/advanced-mapreduce/

It seems the recommended way to use mapreduce is to create the BEAM files and then load them onto the file system where each Riak node can find them as discussed here:
http://docs.basho.com/riak/kv/2.1.4/using/reference/custom-code/

I know how to mount the folder containing the BEAM files in docker, but am struggling with the second set of instructions for loading custom code:

```
Edit app.config and insert an add_paths setting into the riak_kv section as shown:

{riak_kv, [
  %% ...
  {add_paths, ["/tmp/beams/"]},
  %% ...
```

I see a generated config on my docker instance:

```
var/lib/riak/generated.configs/app.2016.10.26.20.00.27.config
```
but since this appears to be auto-generated I suspect I should not mess with it.

Questions:

Is there a default folder that we can mount into the container for custom beam files (for mapreduce)?

Is there a way to update (or mount) the app.config so that we can add the paths ourselves?

Any help is greatly appreciated.  The ability to use custom mapreduce files locally would greatly help with having a local environment.

Thanks.

**Comment by lukebakken** [comment]
You'll want to create an `/etc/riak/advanced.config` file and use the [`add_paths`](http://docs.basho.com/riak/kv/2.1.4/configuring/reference/#other-settings) setting. The contents of `advanced.config` are merged with `riak.conf` when configuration files are generated.

If that does not work as expected, please re-open this issue. Thanks!
